import type { Metadata } from 'next'
import {  Kufam } from 'next/font/google'
import './globals.css'
import Navbar from './components/shared/Navbar'

const kufam = Kufam({ 
  subsets: ['arabic'],
  weight: '500'

})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
  
  }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${kufam.className} leading-5 flex-row justify-center`}>{children}
      </body>
    </html>
  )
}
